version: v1
mig-configs:
  all-disabled-dgx-station-40:
    - device-filter: "0x20B010DE"
      devices: all
      mig-enabled: false
      mig-devices: {}
    - device-filter: "0x1FB010DE"
      devices: all
      mig-enabled: false
      mig-devices: {}

  all-enabled-dgx-station-40:
    - device-filter: "0x20B010DE"
      devices: all
      mig-enabled: true
      mig-devices: {}
    - device-filter: "0x1FB010DE"
      devices: all
      mig-enabled: false
      mig-devices: {}

  all-1g.5gb-dgx-station-40:
    - device-filter: "0x20B010DE"
      devices: all
      mig-enabled: true
      mig-devices:
        "1g.5gb": 7
    - device-filter: "0x1FB010DE"
      devices: all
      mig-enabled: false
      mig-devices: {}

  all-2g.10gb-dgx-station-40:
    - device-filter: "0x20B010DE"
      devices: all
      mig-enabled: true
      mig-devices:
        "2g.10gb": 3
    - device-filter: "0x1FB010DE"
      devices: all
      mig-enabled: false
      mig-devices: {}

  all-3g.20gb-dgx-station-40:
    - device-filter: "0x20B010DE"
      devices: all
      mig-enabled: true
      mig-devices:
        "3g.20gb": 2
    - device-filter: "0x1FB010DE"
      devices: all
      mig-enabled: false
      mig-devices: {}

  all-4g.40gb-dgx-station-40:
    - device-filter: "0x20B010DE"
      devices: all
      mig-enabled: true
      mig-devices:
        "4g.20gb": 1
    - device-filter: "0x1FB010DE"
      devices: all
      mig-enabled: false
      mig-devices: {}

  all-7g.40gb-dgx-station-40:
    - device-filter: "0x20B010DE"
      devices: all
      mig-enabled: true
      mig-devices:
        "7g.40gb": 1
    - device-filter: "0x1FB010DE"
      devices: all
      mig-enabled: false
      mig-devices: {}

  all-balanced-dgx-station-40:
    - device-filter: "0x20B010DE"
      devices: all
      mig-enabled: true
      mig-devices:
        "1g.5gb": 2
        "2g.10gb": 1
        "3g.20gb": 1
    - device-filter: "0x1FB010DE"
      devices: all
      mig-enabled: false
      mig-devices: {}

  balanced-k8s-dgx-station-40:
    # Training
    - device-filter: "0x20B010DE"
      devices: [0]
      mig-enabled: false
      mig-devices: {}

    # Training & Fine-tuning
    - device-filter: "0x20B010DE"
      devices: [1]
      mig-enabled: true
      mig-devices:
        "3g.20gb": 2

    # Development & Fine-tuning
    - device-filter: "0x20B010DE"
      devices: [2]
      mig-enabled: true
      mig-devices:
        "2g.10gb": 3
        "1g.5gb": 1

    # Inference & Development
    - device-filter: "0x20B010DE"
      devices: [4]
      mig-enabled: true
      mig-devices:
        "1g.5gb": 7
    - device-filter: "0x1FB010DE"
      devices: [3]
      mig-enabled: false
      mig-devices: {}
